stfalcon/fwdays

src/Application/Bundle/DefaultBundle/Resources/views/News/_news_list.html.twig, src/Application/Bundle/DefaultBundle/Resources/views/News/index.html.twig, src/Application/Bundle/DefaultBundle/Resources/views/News/last.html.twig
https://redmine.stfalcon.com/issues/19262
=> Feature show all news

app/AppKernel.php, app/config/parameters.ini, composer.json, src/Stfalcon/Bundle/EventBundle/EventListener/PaymentGACommerceListener.php, src/Stfalcon/Bundle/EventBundle/Resources/config/services.xml, src/Stfalcon/Bundle/EventBundle/Service/GACommerce.php
Изменен parameter.ini добавлен параметр GA code
=> Feature ga commerce

src/Stfalcon/Bundle/EventBundle/Resources/views/Referral/index.html.twig
=> Update referral text

src/Application/Bundle/UserBundle/Form/Type/RegistrationFormType.php, src/Application/Bundle/UserBundle/Services/RegistrationFormWithGoogleCaptcha.php
Check captcha only in prod environment
=> Check captcha in prod environment only

web/js/partials/add.js
=> Add event class

src/Application/Bundle/UserBundle/Admin/UserAdmin.php
=> Add search by fullname

src/Application/Bundle/DefaultBundle/Controller/PaymentController.php, src/Application/Bundle/DefaultBundle/EventListener/PromoCodeRequestListener.php, src/Application/Bundle/DefaultBundle/Resources/config/services.yml, web/js/partials/add.js
=> Add promo-code from query

src/Application/Bundle/UserBundle/Entity/User.php, web/js/partials/add.js
=> Add symbol

src/Application/Bundle/DefaultBundle/Service/UrlForRedirect.php
=> Change redirect

src/Application/Bundle/DefaultBundle/Controller/AdminController.php, src/Application/Bundle/DefaultBundle/Entity/TicketCost.php, src/Application/Bundle/DefaultBundle/Resources/views/Admin/addUsers.html.twig
=> Add new admin form

src/Application/Bundle/DefaultBundle/Controller/AdminController.php, src/Application/Bundle/DefaultBundle/Resources/views/Admin/addUsers.html.twig
=> Can change ticket price

app/config/routing.yml
=> Fix google connect

app/Resources/views/layout.html.twig, src/Application/Bundle/DefaultBundle/Controller/AdminController.php, src/Application/Bundle/DefaultBundle/Resources/views/Redesign/login_form.html.twig, src/Application/Bundle/DefaultBundle/Resources/views/Redesign/login_social_btn.html.twig, src/Application/Bundle/DefaultBundle/Resources/views/Statistic/event_statistic.html.twig, src/Application/Bundle/DefaultBundle/Resources/views/Statistic/event_statistic_page.html.twig, src/Application/Bundle/DefaultBundle/Resources/views/Statistic/statistic.html.twig
=> Update statistic, Move gtm script, Add social login btn class

src/Application/Bundle/DefaultBundle/Controller/AdminController.php, src/Application/Bundle/DefaultBundle/Resources/views/Statistic/events_statistic_page.html.twig, src/Application/Bundle/DefaultBundle/Resources/views/Statistic/events_statistic_table.html.twig, src/Application/Bundle/DefaultBundle/Resources/views/Statistic/statistic.html.twig, src/Stfalcon/Bundle/EventBundle/Repository/TicketRepository.php
=> Add checked events

src/Application/Bundle/DefaultBundle/Resources/views/Statistic/events_statistic_page.html.twig
=> Add check all events

src/Application/Bundle/DefaultBundle/Controller/PaymentController.php, src/Stfalcon/Bundle/EventBundle/DataFixtures/ORM/LoadTicketData.php
=> Add user to wanna visit table on ticket create

src/Application/Bundle/DefaultBundle/Controller/AdminController.php
=> Add admin user create to wanna visit events

app/Resources/translations/IbrowsSonataTranslationBundle.uk.yml, app/Resources/translations/SonataAdminBundle.uk.xliff, app/Resources/translations/SonataAdminBundle.uk.yml, app/config/config.yml
=> Add admin translate

app/Resources/translations/messages.en.yml
=> Fix translate

src/Application/Bundle/DefaultBundle/Resources/views/Redesign/cabinet.html.twig
=> Move old events

app/DoctrineMigrations/Version20180726182039.php, app/config/services.yml, app/run-ci-pack.sh, src/Stfalcon/Bundle/EventBundle/Admin/EventAdmin.php, src/Stfalcon/Bundle/EventBundle/Admin/EventAudienceAdmin.php, src/Stfalcon/Bundle/EventBundle/Admin/MailAdmin.php, src/Stfalcon/Bundle/EventBundle/Entity/Event.php, src/Stfalcon/Bundle/EventBundle/Entity/EventAudience.php, src/Stfalcon/Bundle/EventBundle/Entity/Mail.php, src/Stfalcon/Bundle/EventBundle/Resources/config/admin.yml
=> Add audience

src/Application/Bundle/DefaultBundle/Service/TicketService.php, src/Stfalcon/Bundle/EventBundle/Repository/PaymentRepository.php
=> Remove discount if user have not paid ticket

app/Resources/markup/src/styles/partials/event.scss, app/Resources/markup/src/styles/partials/media.scss, app/Resources/markup/src/tutorials/event-new-tutorial.html, app/Resources/views/layout.html.twig, web/styles/partials/event.scss, web/styles/partials/media.scss
=> Revert "Revert: fix new event tutorial, add font awesome lib (c8c8bd88)"

src/Application/Bundle/DefaultBundle/Controller/AdminController.php, src/Application/Bundle/DefaultBundle/Controller/PaymentController.php, src/Application/Bundle/DefaultBundle/Controller/UploadController.php, src/Application/Bundle/DefaultBundle/Service/ReferralService.php, src/Application/Bundle/DefaultBundle/Service/StatisticService.php, src/Application/Bundle/DefaultBundle/Twig/AppDateTimeExtension.php, src/Stfalcon/Bundle/EventBundle/Admin/MailQueueAdmin.php, src/Stfalcon/Bundle/EventBundle/Admin/PaymentAdmin.php, src/Stfalcon/Bundle/EventBundle/Admin/SpeakerAdmin.php, src/Stfalcon/Bundle/EventBundle/Repository/TicketRepository.php
@stfalcon requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/stfalcon/fwdays/
=> Scrutinizer Auto-Fixes
